Repository Project-aniwhere/Aniwhere-BE, pull requests merged in 2025-01, with the labels that each got.

#62 refactor-social-login PR
  src/main/java/com/example/aniwhere/application/auth/jwt/JwtWhitelist.java
  src/main/java/com/example/aniwhere/application/auth/jwt/WhitelistEntry.java
  src/main/java/com/example/aniwhere/application/auth/jwt/filter/JwtTokenFilter.java
  src/main/java/com/example/aniwhere/application/auth/kakao/KakaoApi.java
  src/main/java/com/example/aniwhere/application/auth/kakao/WebClientKakaoCaller.java
  src/main/java/com/example/aniwhere/application/auth/kakao/dto/AccessTokenRequest.java
  src/main/java/com/example/aniwhere/application/auth/kakao/dto/KakaoLogoutResponse.java
  src/main/java/com/example/aniwhere/application/auth/kakao/dto/KakaoProfileResponse.java
  src/main/java/com/example/aniwhere/application/auth/kakao/dto/KakaoRenewalResponse.java
  src/main/java/com/example/aniwhere/application/auth/kakao/dto/KakaoTokenResponse.java
  src/main/java/com/example/aniwhere/application/auth/oauth2/handler/CustomOAuth2SuccessHandler.java
  src/main/java/com/example/aniwhere/application/config/querydsl/QueryDslConfig.java
  src/main/java/com/example/aniwhere/application/config/redis/RedisConfig.java
  src/main/java/com/example/aniwhere/application/config/security/CorsConfig.java
  src/main/java/com/example/aniwhere/application/config/security/SecurityConfig.java
  src/main/java/com/example/aniwhere/controller/token/TokenApiController.java
  src/main/java/com/example/aniwhere/controller/user/OAuth2ApiController.java
  src/main/java/com/example/aniwhere/domain/user/Sex.java
  src/main/java/com/example/aniwhere/domain/user/User.java
  src/main/java/com/example/aniwhere/domain/user/dto/EnumValidator.java
  src/main/java/com/example/aniwhere/domain/user/dto/UserDTO.java
  src/main/java/com/example/aniwhere/domain/user/dto/ValidEnum.java
  src/main/java/com/example/aniwhere/global/error/ErrorCode.java
  src/main/java/com/example/aniwhere/global/error/exception/KakaoException.java
  src/main/java/com/example/aniwhere/repository/user/UserRepository.java
  src/main/java/com/example/aniwhere/service/redis/RedisService.java
  src/main/java/com/example/aniwhere/service/user/KakaoService.java
  src/main/java/com/example/aniwhere/service/user/PrincipalOAuthDetailsService.java
Labels: bug, In Progress, Refactoring, Improvement, Code Review

#64 Fix weekend anime
  src/main/java/com/example/aniwhere/controller/anime/controller/AnimeController.java
  src/main/java/com/example/aniwhere/domain/anime/dto/AnimeDTO.java
  src/main/java/com/example/aniwhere/repository/anime/repository/AnimeCustomRepository.java
  src/main/java/com/example/aniwhere/repository/anime/repository/AnimeCustomRepositoryImpl.java
  src/main/java/com/example/aniwhere/service/anime/service/AnimeService.java
Labels: 🎨애니메이션 도메인

#69 feature-picked-anime PR
  .gitignore
  build.gradle
  src/main/java/com/example/aniwhere/application/auth/jwt/JwtWhitelist.java
  src/main/java/com/example/aniwhere/application/config/page/PageRequest.java
  src/main/java/com/example/aniwhere/application/config/page/PageResponse.java
  src/main/java/com/example/aniwhere/application/config/redis/RedisConfig.java
  src/main/java/com/example/aniwhere/application/config/security/SecurityConfig.java
  src/main/java/com/example/aniwhere/controller/pickedAnime/PickedAnimeApiController.java
  src/main/java/com/example/aniwhere/controller/user/OAuth2ApiController.java
  src/main/java/com/example/aniwhere/domain/pickedAnime/PickedAnime.java
  src/main/java/com/example/aniwhere/domain/pickedAnime/dto/PickedAnimeDto.java
  src/main/java/com/example/aniwhere/domain/user/User.java
  src/main/java/com/example/aniwhere/global/error/ErrorCode.java
  src/main/java/com/example/aniwhere/repository/pickedAnime/PickedAnimeRepository.java
  src/main/java/com/example/aniwhere/repository/pickedAnime/PickedAnimeRepositoryCustom.java
  src/main/java/com/example/aniwhere/repository/pickedAnime/PickedAnimeRepositoryImpl.java
  src/main/java/com/example/aniwhere/repository/pickedAnime/RedisLockRepository.java
  src/main/java/com/example/aniwhere/service/pickedAnime/LettuceLockPickedAnimeFacade.java
  src/main/java/com/example/aniwhere/service/pickedAnime/PickedAnimeService.java
Labels: ✨기능 구현, 🔄피드백에 따른 개선 요청, 👀코드리뷰, ❤️찜

#73 feat-admin PR
  src/main/java/com/example/aniwhere/application/auth/oauth2/KakaoUserInfo.java
  src/main/java/com/example/aniwhere/application/auth/oauth2/OAuth2UserInfo.java
  src/main/java/com/example/aniwhere/application/config/security/MyUserDetails.java
  src/main/java/com/example/aniwhere/application/config/security/SecurityConfig.java
  src/main/java/com/example/aniwhere/controller/admin/AdminApiController.java
  src/main/java/com/example/aniwhere/controller/admin/UserSearchCondition.java
  src/main/java/com/example/aniwhere/controller/episodes/EpisodeApiController.java
  src/main/java/com/example/aniwhere/controller/history/HistoryApiController.java
  src/main/java/com/example/aniwhere/controller/user/UserApiController.java
  src/main/java/com/example/aniwhere/domain/admin/dto/EvaluationRequestDto.java
  src/main/java/com/example/aniwhere/domain/admin/dto/EvaluationResponseDto.java
  src/main/java/com/example/aniwhere/domain/admin/dto/Status.java
  src/main/java/com/example/aniwhere/domain/admin/dto/UserListDto.java
  src/main/java/com/example/aniwhere/domain/casting/Casting.java
  src/main/java/com/example/aniwhere/domain/episodeReviews/EpisodeReviews.java
  src/main/java/com/example/aniwhere/domain/episodes/Episodes.java
  src/main/java/com/example/aniwhere/domain/history/History.java
  src/main/java/com/example/aniwhere/domain/history/Status.java
  src/main/java/com/example/aniwhere/domain/history/dto/AdminHistoryResponseDto.java
  src/main/java/com/example/aniwhere/domain/history/dto/HistoryUserDto.java
  src/main/java/com/example/aniwhere/domain/history/dto/HistoryUserResponseDto.java
  src/main/java/com/example/aniwhere/domain/history/dto/RequestHistoryResponseDto.java
  src/main/java/com/example/aniwhere/domain/pickedAnime/PickedAnime.java
  src/main/java/com/example/aniwhere/domain/review/Review.java
  src/main/java/com/example/aniwhere/domain/token/RefreshToken.java
  src/main/java/com/example/aniwhere/domain/user/User.java
  src/main/java/com/example/aniwhere/global/common/Common.java
  src/main/java/com/example/aniwhere/global/error/ErrorCode.java
  src/main/java/com/example/aniwhere/repository/episodes/EpisodesRepositoryCustom.java
  src/main/java/com/example/aniwhere/repository/episodes/EpisodesRepositoryImpl.java
  src/main/java/com/example/aniwhere/repository/episodesReview/EpisodesReviewRepositoryCustom.java
  src/main/java/com/example/aniwhere/repository/episodesReview/EpisodesReviewRepositoryImpl.java
  src/main/java/com/example/aniwhere/repository/history/HistoryRepository.java
  src/main/java/com/example/aniwhere/repository/user/UserCustomRepository.java
  src/main/java/com/example/aniwhere/repository/user/UserCustomRepositoryImpl.java
  src/main/java/com/example/aniwhere/repository/user/UserRepository.java
  src/main/java/com/example/aniwhere/service/admin/AdminService.java
  src/main/java/com/example/aniwhere/service/history/HistoryService.java
  src/main/java/com/example/aniwhere/service/user/MyUserDetailsService.java
Labels: ✨기능 구현, 👀코드리뷰
